# Generated by Django 5.2.1 on 2025-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpulse', '0003_task_board_task_deadline_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
